howdimain/urls.py
from django.conf.urls import include
from django.urls import path
from django.conf import settings

from django.conf.urls.static import static

urlpatterns = [
    path('', include('boards.urls')),
    path('', include('accounts.urls')),
    path('', include('newsfeed.urls')),
    path('', include('stock.urls')),
    path('', include('music.urls')),
    path('martor/', include('martor.urls')),
]

if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)
    urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)

music/urls.py
from django.urls import path
from .views import PlayTopTracksView, PlayListView


urlpatterns = [
    path("music/play_top_tracks/", PlayTopTracksView.as_view(), name="play_top_tracks"),
    path("music/playlist/<int:sort_choice>/", PlayListView.as_view(), name="playlist"),
]

stock/urls.py
from django.urls import path
from stock.views import quotes, portfolios, plots, news

urlpatterns = [
    path('finance/stock_quote/', quotes.QuoteView.as_view(), name='stock_quotes'),

    path('finance/stock_news/<str:source>/<str:symbol>/',
         news.StockNewsView.as_view(), name='stock_news'),

    path('finance/stock_press/<str:source>/<str:symbol>/',
         news.StockPressView.as_view(), name='stock_press'),

    path('finance/stock_intraday/<str:source>/<str:symbol>/',
         plots.IntraDayView.as_view(), name='stock_intraday'),

    path('finance/stock_history/<str:source>/<str:symbol>/<str:period>/',
         plots.HistoryView.as_view(), name='stock_history'),

    path('finance/portfolio/', portfolios.PortfolioView.as_view(), name='portfolio'),
]

stock/models.py
import datetime
from django.db import models
from django.contrib.auth.models import User
from django.utils.text import Truncator


class Person(User):
    """this is a proxy for User"""

    class Meta:
        proxy = True

    def get_portfolio_names(self) -> list[str]:
        return [
            p.portfolio_name for p in self.portfolios.all().order_by("portfolio_name")
        ]


class Currency(models.Model):
    currency = models.CharField(max_length=3, unique=True)
    usd_exchange_rate = models.CharField(max_length=20, default="1.0")

    def get_exchangerate(self) -> str:
        return self.usd_exchange_rate

    def get_exchangerate_on_date(self, currency_date: str) -> str:
        if currency_date:
            currency = self.history.filter(currency_date=currency_date)
            return currency.last().usd_exchange_rate if currency else self.usd_exchange_rate

        else:
            return self.usd_exchange_rate

    def __str__(self) -> str:
        return str(self.currency)


class CurrencyHistory(models.Model):
    currency = models.ForeignKey(
        Currency, on_delete=models.CASCADE, related_name="history"
    )
    currency_date = models.DateField()
    usd_exchange_rate_low = models.CharField(max_length=20, default="1.0")
    usd_exchange_rate_high = models.CharField(max_length=20, default="1.0")
    usd_exchange_rate = models.CharField(max_length=20, default="1.0")
    created_at = models.DateTimeField(auto_now_add=True, null=True, blank=True)

    def __str__(self) -> str:
        return (
            f"{self.currency_date.strftime('%d-%m-%Y')}: "
            f"{self.currency.currency}, "
            f"{self.usd_exchange_rate}, "
            f"{self.usd_exchange_rate_low}, "
            f"{self.usd_exchange_rate_high}"
        )


class Exchange(models.Model):
    mic = models.CharField(max_length=5, unique=True)
    ric = models.CharField(max_length=5, unique=False, default=None)
    name = models.CharField(max_length=50, unique=True)
    acronym = models.CharField(max_length=15, unique=True)
    country_code = models.CharField(max_length=5, unique=False)
    city = models.CharField(max_length=20, unique=False)
    website = models.CharField(max_length=50, unique=False)
    timezone = models.CharField(max_length=30)
    currency = models.ForeignKey(
        Currency, on_delete=models.CASCADE, related_name="exchanges"
    )

    def __str__(self) -> str:
        return str(self.name)


class Stock(models.Model):
    symbol = models.CharField(max_length=20, unique=True)
    symbol_ric = models.CharField(max_length=20, unique=True)
    company = models.CharField(max_length=75, unique=False)
    type = models.CharField(max_length=10, blank=True, null=True, default=None)
    currency = models.ForeignKey(Currency, on_delete=models.CASCADE)
    exchange = models.ForeignKey(
        Exchange, on_delete=models.CASCADE, related_name="stocks"
    )

    def mic(self) -> str:
        return self.exchange.mic

    def ric(self) -> str:
        return self.exchange.ric

    def __str__(self) -> str:
        return Truncator(self.company).chars(20)


class Portfolio(models.Model):
    portfolio_name = models.CharField(max_length=20)
    user = models.ForeignKey(
        Person, on_delete=models.CASCADE, related_name="portfolios"
    )

    class Meta:
        unique_together = ["portfolio_name", "user"]

    def get_stock(self) -> dict:
        return {stock.stock.symbol_ric: stock.quantity for stock in self.stocks.all()}

    def get_stock_on_date(self, trading_date: str) -> dict:
        return {stock.stock_history.stock.symbol_ric: stock.quantity for stock in self.history.filter(trading_date=trading_date)}

    def __str__(self) -> str:
        return f"{self.portfolio_name} for {self.user.username}"


class StockSelection(models.Model):
    stock = models.ForeignKey(Stock, on_delete=models.CASCADE)
    quantity = models.CharField(max_length=20, default=0.0)
    portfolio = models.ForeignKey(
        Portfolio, on_delete=models.CASCADE, related_name="stocks"
    )

    class Meta:
        unique_together = ["stock", "portfolio"]

    def __str__(self) -> str:
        return (
            f"{self.portfolio.user.username}, {self.portfolio.portfolio_name}: "
            f"{self.stock.symbol}, {self.quantity}"
        )


class StockHistory(models.Model):
    stock = models.ForeignKey(Stock, on_delete=models.CASCADE, related_name='history')
    last_trading_time = models.DateTimeField()
    open = models.CharField(max_length=20, default=0.0)
    latest_price = models.CharField(max_length=20, default=0.0)
    day_low = models.CharField(max_length=20, default=0.0)
    day_high = models.CharField(max_length=20, default=0.0)
    volume = models.CharField(max_length=20, default=0.0)
    close_yesterday = models.CharField(max_length=20, default=0.0)
    change_pct = models.CharField(max_length=20, default=0.0)
    day_change = models.CharField(max_length=20, default=0.0)
    created_at = models.DateTimeField(auto_now_add=True, null=True, blank=True)

    class Meta:
        unique_together = ["stock", "last_trading_time"]

    def __str__(self) -> str:
        return (
            f"\n{self.stock.symbol_ric}:\n"
            f"last trading time: {self.last_trading_time.strftime("%d-%m-%Y %H:%M")}\n"
            f"close yesterday: {self.close_yesterday}, open: {self.open}, price: {self.latest_price}, \n"
            f"day_low: {self.day_low}, day_high: {self.day_high}, volume: {self.volume}, \n"
            f"change: {self.day_change}, percentage: {self.change_pct}\n"
        )


class PortfolioHistory(models.Model):
    portfolio = models.ForeignKey(Portfolio, on_delete=models.CASCADE, related_name='history')
    trading_date = models.DateField()
    quantity = models.CharField(max_length=20, default=0.0)
    stock_history = models.ForeignKey(StockHistory, on_delete=models.CASCADE)
    created_at = models.DateTimeField(auto_now_add=True, null=True, blank=True)

    class Meta:
        unique_together = ["portfolio", "stock_history"]

    def __str__(self) -> str:
        return (
            f"\nPortfolio {self.portfolio.portfolio_name} on {self.trading_date.strftime("%d-%m-%Y")}\n"
            f"{self.quantity} {self.stock_history.stock.symbol_ric}, last price: {self.stock_history.latest_price}"
        )

stock/views/news.py
from django.shortcuts import render
from django.views.generic import View
from howdimain.utils.plogger import Logger
from stock.module_stock import TradingData

logger = Logger.getlogger()


class StockNewsView(View):

    template_name = 'finance/stock_news.html'
    td = TradingData()
    td.setup()
    data_provider_url = td.data_provider_url

    def get(self, request, source, symbol):
        stock_news = self.td.get_stock_news(symbol)
        context = {
            'source': source,
            'symbol': symbol,
            'company': self.td.get_company_name(symbol),
            'stock_news': stock_news,
        }
        return render(request, self.template_name, context)


class StockPressView(View):

    template_name = 'finance/stock_press.html'
    td = TradingData()
    td.setup()
    data_provider_url = td.data_provider_url

    def get(self, request, source, symbol):
        stock_press = self.td.get_stock_press(symbol)
        context = {
            'source': source,
            'symbol': symbol,
            'company': self.td.get_company_name(symbol),
            'stock_press': stock_press,
        }
        return render(request, self.template_name, context)

stock/views/quotes.py
import datetime
from django.shortcuts import render
from django.views.generic import View
from stock.models import Person, Portfolio
from stock.module_stock import TradingData
from stock.forms import StockQuoteForm
from howdimain.howdimain_vars import MARKETS, STOCK_DETAILS, MAX_SYMBOLS_ALLOWED
from howdimain.utils.get_ip import get_client_ip
from howdimain.utils.format_and_tokens import add_display_tokens, format_and_sort_stocks
from howdimain.utils.plogger import Logger


logger = Logger.getlogger()
source = "quotes"


class QuoteView(View):
    stockquote_form = StockQuoteForm
    template_name = "finance/stock_quotes.html"
    td = TradingData()
    td.setup()
    data_provider_url = td.data_provider_url

    def get(self, request):
        user = request.user
        if user.is_authenticated:
            # add Person class to user
            user.__class__ = Person

        logger.info(
            f"{self.request.user} [{get_client_ip(self.request)}] "
            f"clicked on menu Quote"
        )
        selected_portfolio = request.session.get("selected_portfolio", "")
        stockdetail = request.session.get("stockdetail", STOCK_DETAILS[0][0])
        markets = request.session.get("markets", MARKETS)
        quote_string = ""
        datepicked = datetime.datetime.now().strftime("%d/%m/%Y")

        portfolio = self.select_portfolio(user, selected_portfolio)
        if portfolio:
            symbols = list(portfolio.get_stock().keys())
            stock_info = self.td.get_stock_trade_info(symbols[0:MAX_SYMBOLS_ALLOWED])
            stock_info += self.td.get_stock_trade_info(
                symbols[MAX_SYMBOLS_ALLOWED : 2 * MAX_SYMBOLS_ALLOWED]
            )
        else:
            symbols = self.td.parse_stock_quote(quote_string, markets=markets)
            stock_info = self.td.get_stock_trade_info(symbols[0:MAX_SYMBOLS_ALLOWED])
            selected_portfolio = ""

        form = self.stockquote_form(
            user=user,
            initial={
                "quote_string": quote_string,
                "portfolios": selected_portfolio,
                "markets": markets,
                "stockdetails": stockdetail,
                "datepicked": datepicked,
                "date_is_today": True,
            },
        )
        stock_info = add_display_tokens(stock_info)
        stock_info = format_and_sort_stocks(stock_info)
        context = {
            "source": source,
            "stock_info": stock_info,
            "form": form,
            "data_provider_url": self.data_provider_url,
        }
        return render(request, self.template_name, context)

    def post(self, request):
        user = request.user
        if user.is_authenticated:
            # add Person class to user
            user.__class__ = Person

        date_today = datetime.datetime.now().date().strftime("%d/%m/%Y")
        quote_string = request.session.get("quote_string", "")
        selected_portfolio = request.session.get("selected_portfolio", "")
        datepicked = request.session.get("datepicked", date_today)
        markets = request.session.get("markets", MARKETS)
        stockdetail = request.session.get("stockdetail", STOCK_DETAILS[0][0])
        date_is_today = True

        form = self.stockquote_form(request.POST, user=user)
        if form.is_valid():
            form_data = form.cleaned_data
            new_quote_string = form_data.get("quote_string")
            new_selected_portfolio = form_data.get("portfolios")
            markets = form_data.get("markets")
            stockdetail = form_data.get("stockdetails")
            datepicked = form_data.get("datepicked").strftime("%d/%m/%Y")
            date_is_today = True if datepicked == date_today else False

            if new_selected_portfolio != selected_portfolio:
                selected_portfolio = new_selected_portfolio
                quote_string = ""
            elif new_quote_string != quote_string:
                quote_string = new_quote_string
                selected_portfolio = ""
            else:
                pass

            portfolio = self.select_portfolio(user, selected_portfolio)
            if portfolio and datepicked == date_today:
                symbols = list(portfolio.get_stock().keys())
                stock_info = self.td.get_stock_trade_info(
                    symbols[0:MAX_SYMBOLS_ALLOWED]
                )
                stock_info += self.td.get_stock_trade_info(
                    symbols[MAX_SYMBOLS_ALLOWED : 2 * MAX_SYMBOLS_ALLOWED]
                )

            elif portfolio:
                dateval_query = datetime.datetime.strptime(
                    datepicked, "%d/%m/%Y"
                ).strftime("%Y-%m-%d")
                symbols = list(portfolio.get_stock_on_date(dateval_query).keys())
                stock_info = self.td.get_stock_trade_info_on_date(
                    dateval_query, symbols
                )
            else:
                datepicked = date_today
                symbols = self.td.parse_stock_quote(quote_string, markets=markets)
                stock_info = self.td.get_stock_trade_info(
                    symbols[0:MAX_SYMBOLS_ALLOWED]
                )
                selected_portfolio = ""

            logger.info(
                f"{user} [{get_client_ip(request)}] looking up: "
                f"{quote_string} / {selected_portfolio}"
            )
        else:
            stock_info = []

        form = self.stockquote_form(
            user=user,
            initial={
                "quote_string": quote_string,
                "portfolios": selected_portfolio,
                "markets": markets,
                "stockdetails": stockdetail,
                "datepicked": datepicked,
                "date_is_today": date_is_today,
            },
        )
        request.session["quote_string"] = quote_string
        request.session["selected_portfolio"] = selected_portfolio
        request.session["markets"] = markets
        request.session["stockdetail"] = stockdetail
        request.session["datepicked"] = datepicked

        stock_info = add_display_tokens(stock_info)
        stock_info = format_and_sort_stocks(stock_info)
        context = {
            "source": source,
            "stock_info": stock_info,
            "form": form,
            "data_provider_url": self.data_provider_url,
        }
        return render(request, self.template_name, context)

    def select_portfolio(self, user, selected_portfolio):
        portfolio = None
        if selected_portfolio:
            try:
                if user.is_authenticated:
                    portfolio = Portfolio.objects.get(
                        user=user, portfolio_name=selected_portfolio
                    )
                else:
                    raise Portfolio.DoesNotExist

            except Portfolio.DoesNotExist:
                try:
                    default_user = Person.objects.get(username="default_user")
                    portfolio = Portfolio.objects.get(
                        user=default_user, portfolio_name=selected_portfolio
                    )
                except (Person.DoesNotExist, Portfolio.DoesNotExist):
                    pass

        return portfolio

stock/templates/finance/stock_intraday.html
{% extends 'base.html' %}<html>

{% load static stock_tags %}

{%block title %}Latest stock trading{% endblock %}

{% block navbutton %}
<li class="nav-item dropdown">
  <a class="nav-link dropdown-toggle me-auto" href="#" role="button" data-bs-toggle="dropdown">
    Latest stock trading
  </a>
  <ul class="dropdown-menu">
    {% if source == 'quotes' %}
    <li><a class="dropdown-item" href="{% url 'stock_quotes' %}">Quotes</a></li>
    {% else %}
    <li><a class="dropdown-item" href="{% url 'portfolio' %}">Portfolio</a></li>
    {% endif %}
    <li><a class="dropdown-item" href="{% url 'home' %}">Home</a></li>
  </ul>
</li>
{% endblock %}

{% block content %}
<div class="flex-d" id="chart-container">FusionCharts()</div>
<div>
  <button class="btn btn-primary btn-sm"
    onclick="window.location.href='{% url 'stock_news' source stock_symbol %}'">Stock news</button>
  <button class="btn btn-primary btn-sm"
    onclick="window.location.href='{% url 'stock_press' source stock_symbol %}'">Press releases</button>
  {% for period in periods reversed %}
  {% if period == periods|index:-1 %}
  <button class="btn btn-primary btn-sm"
    onclick="window.location.href='{% url 'stock_history' source stock_symbol period %}'">History ({{period}})</button>
  {% else %}
  {% if period|add:0 > 1 %}
  <button class="btn btn-primary btn-sm"
    onclick="window.location.href='{% url 'stock_history' source stock_symbol period %}'">{{period}} years</button>
  {% else %}
  <button class="btn btn-primary btn-sm"
    onclick="window.location.href='{% url 'stock_history' source stock_symbol period %}'">{{period}} year</button>
  {% endif %}
  {% endif %}
  {% endfor %}
</div>
<br>
<small>Data provided by <a href="https://{{ data_provider_url }}" target="_blank">{{ data_provider_url }}</a></small>
<br><br><br><br>

{% endblock content %}

{% block javascript %}
<script type="text/javascript" src="{% static 'fusioncharts/types/fusioncharts.js' %}"></script>
<script type="text/javascript" src="{% static 'fusioncharts/themes/fusioncharts.theme.candy.js' %}"></script>
<script type="text/javascript" src="{% static 'fusioncharts/themes/fusioncharts.theme.fusion.js' %}"></script>
{{ chart_js|safe }}
{% endblock javascript %}

stock/templates/finance/stock_portfolio.html
{% extends 'base.html' %}

{% load static %}
{% load crispy_forms_tags %}
{% load stock_tags %}

{% block title %}Portfolio{% endblock %}

{% block stylesheet %}{% endblock %}

{% block navbutton %}
<li class="nav-item dropdown">
  <a class="nav-link dropdown-toggle me-auto" href="#" role="button" data-bs-toggle="dropdown">
    Portfolio
  </a>
  <ul class="dropdown-menu">
    <li><a class="dropdown-item" href="{% url 'stock_quotes' %}">Stock Quotes</a></li>
    <li><a class="dropdown-item" href="{% url 'home' %}">Home</a></li>
  </ul>
</li>
{% endblock %}

{% block content %}
<form id="id_portfolio" method="post">
  {% csrf_token %}
  <a style="display: none">{{ form.new_portfolio }} {{ form.portfolio_name }} {{ form.portfolios }}
    {{ form.currencies }} {{ form.symbol }} {{ form.stockdetails }}
  </a>

  <div class="d-inline-flex flex-wrap">
    <div class="dropdown">
      <button type="button" class="dropdown-toggle btn btn-outline-primary btn-sm mt-1">
        {% if form.portfolio_name.value == '' %}
        Portfolio
        {% else %}
        {{ form.portfolios.value }}
        {% endif %}
      </button>
      <div class="dropdown-content">
        {% if form.date_is_today.value %}
        <button class="btn btn-primary btn-sm mb=1 mb-1" name="btn1_pressed" value="new_portfolio"
          onclick="return PromptNewPortfolioName()">New</button>
        {% if form.portfolio_name.value != '' %}
        <button class="btn btn-primary btn-sm mb-1" name="btn1_pressed" value="rename_portfolio"
          onclick="return RenamePortfolio('{{ form.portfolio_name.value }}')">
          Rename</button>
        <button class="btn btn-primary btn-sm mb-1" name="btn1_pressed" value="copy_portfolio"
          onclick="return CopyPortfolio('{{ form.portfolio_name.value }}')">
          Copy</button>
        <button class="btn btn-primary btn-sm" name="btn1_pressed" value="delete_portfolio"
          onclick="return ConfirmDeletePortfolio('{{ form.portfolio_name.value }}')">
          Delete</button>
        {% endif %}
        <div class="dropdown-divider"></div>
        {% endif %}
        {% for portfolio in form.portfolios %}
        {% if not portfolio.data.selected %}
        <button class="btn btn-link text-nowrap" value="{{ portfolio.data.value}}" name="{{ portfolio.data.name }}">
          <a>{{ portfolio.choice_label }}</a></button>
        {% endif %}
        {% endfor %}
      </div>
    </div>
    {% if form.portfolio_name.value != '' %}
    {{ form.datepicked }}
    {% if form.date_is_today.value %}
    <button class="btn btn-outline-primary btn-sm ms-1 mt-1" name="btn1_pressed" value="add_symbol"
      onclick="return AddSymbol('{{ form.symbol.value }}')">Add symbol
    </button>
    {% endif %}
    <div class="dropdown">
      <button type="button" class="btn dropdown-toggle btn-outline-primary btn-sm ms-1 mt-1">
        {{ form.stockdetails.value }}
      </button>
      <div class="dropdown-content">
        {% for stockdetail in form.stockdetails %}
        {% if not stockdetail.data.selected %}
        <button class="btn btn-link text-nowrap" value="{{ stockdetail.data.value }}"
          name="{{ stockdetail.data.name }}">{{stockdetail.choice_label }}
        </button>
        {% endif %}
        {% endfor %}
      </div>
    </div>
    <div class="dropdown">
      <button type="button" class="btn dropdown-toggle btn-outline-primary btn-sm ms-1 mt-1">
        {{ form.currencies.value }}</button>
      <div class="dropdown-content">
        {% for currency in form.currencies %}
        {% if not currency.data.selected %}
        <button class="btn btn-link text-nowrap" value="{{ currency.data.value }}" name="{{ currency.data.name }}">
          {{ currency.choice_label }}</button>
        {% endif %}
        {% endfor %}
      </div>
    </div>
    {% endif %}
  </div>
  {% if form.portfolio_name.value != '' %}
  <div class="d-flex float-lg-right mt-2">
    <strong class="me-2">Value:</strong>
    <strong class="me-2">{{ totals.value }}</strong>
    <strong class="me-1">Change:</strong>
    <strong class="me-2" style="color:{{ totals.color }}">{{ totals.caret}} {{ totals.value_change }}</strong>
    <strong class="me-2">{{ exchangerate }}</strong>
  </div>
  {% endif %}

  <div class="text-nowrap mt-2 mb-2" style="overflow: hidden; clear:both">
    <table id="dtHorizontalVerticalScroll" class="table table-striped table-responsive table-sm" cellspacing="0"
      width="100%">
      <thead class="col-sm-8 custom-thead-grey">
        <tr>
          <th width="17%">Company</th>
          <th width="10%">Symbol</th>
          <th width="10%">Currency</th>
          <th width="10%">Price</th>
          <th width="10%">Qty</th>
          <th width="10%">Value<br>({{form.currencies.value}})</th>
          <th width="3%"></th>
          <th width="10%">Change<br>({{form.currencies.value}})</th>
          <th width="10%"></th>
          <th width="10%"></th>
        </tr>
      </thead>
      <tbody>
        {% increment -1 as change_btn_counter %}
        {% for stock in stocks %}
        <tr>
          {% if form.stockdetails.value == form.stockdetails.field.choices.0.0 %}
          <td width="17%"><a class="btn-link" href="{% url 'stock_intraday' source stock.symbol %}">
              {{ stock.name|truncatechars:20 }}</a>
          </td>
          {% elif form.stockdetails.value == form.stockdetails.field.choices.1.0 %}
          <td width="17%"><a class="btn-link" href="{% url 'stock_news' source stock.symbol %}">
              {{ stock.name|truncatechars:20 }}</a>
          </td>
          {% elif form.stockdetails.value == form.stockdetails.field.choices.2.0 %}
          <td width="17%"><a class="btn-link" href="{% url 'stock_press' source stock.symbol %}">
              {{ stock.name|truncatechars:20 }}</a>
          </td>
          {% endif %}
          <td width="10%">{{ stock.symbol }}</td>
          <td width="10%">{{ stock.currency }}</td>
          <td width="10%">{{ stock.price }}</td>

          {% if stock.currency != 'N/A' %}
          <td width="10%">{{ stock.quantity }}</td>
          <td width="10%">{{ stock.value }}</td>
          <td style="width: 3%; color:{{ stock.font_color }}">{{ stock.caret_up_down }}</td>
          <td style="width: 10%; color:{{ stock.font_color }}">{{ stock.value_change }}</td>
          {% if form.date_is_today.value %}
          <td width="10%">
            <button class="btn btn-outline-secondary btn-sm" name="change_qty_btn_pressed" value="{{ stock.symbol }}, "
              onclick="return ChangeQuantity('{{ stock.name }}', '{{ stock.quantity }}', '{{ change_btn_counter }}')">Change</button>
          </td>
          {% increment change_btn_counter as change_btn_counter %}
          {% else %}
          <td width="10%"></td>
          {% endif %}
          {% else %}
          <td width="10%"></td>
          <td width="10%"></td>
          <td style="width:3%"></td>
          <td width="10%"></td>
          <td width="10%"></td>
          {% endif %}

          {% if form.date_is_today.value %}
          <td width="10%">
            <button class="btn btn-outline-secondary btn-sm" name="delete_symbol_btn_pressed" value="{{ stock.symbol }}"
              onclick="return ConfirmDeleteSymbol('{{ stock.name }}' )">Delete</button>
          </td>
          {% else %}
          <td width="10%"></td>
          {% endif %}
        </tr>
        {% endfor %}
      </tbody>
    </table>
  </div>
  <small>Data provided by <a href="https://{{ data_provider_url }}" target="_blank">{{ data_provider_url }}</a></small>

</form>
<br><br><br><br>
{% endblock content %}

{% block javascript %}
<script type="text/javascript" src="{% static 'js/datepicker.min.js' %}"></script>
<script>
  var form = document.getElementById('id_portfolio');

  function PromptNewPortfolioName() {
    var newPortfolio = prompt('What is the name of the new portfolio', '');

    if (newPortfolio != null && newPortfolio != '' && newPortfolio != "''") {
      form.new_portfolio.value = newPortfolio;
      return true;
    }
    else {
      return false;
    }
  }

  function RenamePortfolio(name) {
    var newName = prompt('Give a new name for portfolio: ' + name);

    if (newName != null && newName != '' && newName != "''") {
      form.portfolio_name.value = newName;
      return true;
    }
    else {
      return false;
    }
  }

  function CopyPortfolio(name) {
    var newName = prompt('Give a name for the copied portfolio: ' + name);

    if (newName != null && newName != '' && newName != "''" && newName != name) {
      form.new_portfolio.value = newName;
      return true;
    }
    else {
      return false;
    }
  }

  function ConfirmDeletePortfolio(portfolio) {
    confirmed = confirm('Do you really want to delete portfolio: ' + portfolio + '?');
    if (confirmed) {
      return true;
    }
    else {
      return false;
    }
  }

  function AddSymbol(symbol) {
    var newSymbol = prompt('Add a stock symbol', symbol);

    if (newSymbol != null && newSymbol != '' && newSymbol != "''") {
      form.symbol.value = newSymbol;
      return true;
    }
    else {
      return false;
    }
  }

  function ChangeQuantity(name, qty, counter) {
    var newQuantity = prompt('Change quantity for ' + name, qty);
    newQuantity = parseFloat(newQuantity);
    qty = parseFloat(qty);

    if (newQuantity >= 0 && newQuantity != qty) {
      // if there is only one change button then change_qty_btn_pressed is not an array
      try {
        var a = form.change_qty_btn_pressed[counter].value;
        form.change_qty_btn_pressed[counter].value += newQuantity;
      }
      catch (err) {
        form.change_qty_btn_pressed.value += newQuantity;
      }
      return true;
    }
    else {
      return false;
    }
  }

  function ConfirmDeleteSymbol(companyName) {
    confirmed = confirm('Do you really want to delete ' + companyName + '?');
    if (confirmed) {
      return true;
    }
    else {
      return false;
    }
  }

  $('#id_datepicked').change(function () {
    form.submit()
  })

</script>
{% endblock %}